### ISSUE TITLE
Questions about the GSoC 2018 project

### ISSUE THREAD

**Issue by nctl144** [scrapy/scrapy-bench#19]
After doing some research about the GSoC 2018, I noticed that the benchmarker is mentioned in a new project called "Scrapy Performance Improvement". There are some bottleneck components that this project is aiming to measure and improve. Therefore, can you guys please tell me more about it? I am interested and want to implement a simple version of it just to see how it works?
As I am free this summer so I think it would be a good chance for me to learn more!

**Comment by lopuhin** [comment]
That's awesome that you are interested!

One area is that scrapy performance under Python 3 is lower than under Python 2: the difference can range from 15% to 2x depending on the benchmark, with 2x for ``scrapy bench``: https://github.com/scrapy/scrapy/issues/3134

We also started collecting other performance issues under "performance" label: https://github.com/scrapy/scrapy/issues?q=is%3Aissue+is%3Aopen+label%3Aperformance

There can also be other performance issues not covered by current benchmarks, so adding new benchmarks can also be useful, specially if they help to narrow down the problem. They also help to profile, diagnose and then make sure that the problem is solved.

**Comment by nctl144** [comment]
So the new project aims to expand this benchmark project as we need to add new benchmarks to measure other performance issues, am I correct? I will do some research on this!

**Comment by lopuhin** [comment]
> So the new project aims to expand this benchmark project as we need to add new benchmarks to measure other performance issues, am I correct?

Not quite, the goal is to improve scrapy performance, so this benchmarking project is just a tool. I expect main changes to be made to scrapy and it's dependencies. But obviously understanding the benchmarking suite is also important to succeed.
